[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ConcurrentCollections = "5060bff5-0b44-40c5-b522-fcd3ca5cecdd"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
